services:
    bruninoit.wvtt.listener:
        class: bruninoit\wvtt\event\main_listener
        arguments:
            - @controller.helper
            - @template
            - @db
            - @user
            - %bruninoit.wvtt.tables.wvtt%
        tags:
            - { name: event.listener }
