imports:
    - { resource: tables.yml }
services:
    bruninoit.wvtt.listener:
        class: bruninoit\wvtt\event\main_listener
        arguments:
            - @controller.helper
            - @template
            - @dbal.conn
            - @user
            - %core.root_path%
            - %core.php_ext%
            - %bruninoit.wvtt.tables.wvtt%
            - @auth
        tags:
            - { name: event.listener }
